CREATE SEQUENCE "PREMIUM_ENTITY_SEQ"
MINVALUE 1
MAXVALUE 999999999
INCREMENT BY 50
START WITH 1
NOCACHE
NOCYCLE;

create table PREMIUM_ENTITY(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CLIENT_ID VARCHAR(128),
    DATE VARCHAR(128),
    PREMIUM VARCHAR(128)
);